---
# handlers file for arillso.shorewall

- name: enable shorewall
  become: true
  service: name={{ shorewall_service_name }} enabled=yes state=started
  when: (shorewall_package_state != "absent")

- name: enable shorewall6 
  become: true
  service: name={{ shorewall6_service_name }} enabled=yes state=started
  when: (shorewall6_package_state != "absent")

- name: restart shorewall
  become: true
  service: name={{ shorewall_service_name }} state=restarted

- name: restart shorewall6
  become: true
  service: name={{ shorewall6_service_name }} state=restarted